server.name: kibana
server.host: 0.0.0.0
server.ssl:
  enabled: true
  certificate: /usr/share/kibana/config/certs/kibana/kibana.crt
  key: /usr/share/kibana/config/certs/kibana/kibana.key
  certificateAuthorities: /usr/share/kibana/config/certs/ca/ca.crt

elasticsearch.ssl.certificateAuthorities: /usr/share/kibana/config/certs/ca/ca.crt

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true
elasticsearch.hosts: [ https://elasticsearch:9200 ]
elasticsearch.username: kibana_system
elasticsearch.password: 0*043rFuAb0uB1RvRG2x

xpack.encryptedSavedObjects.encryptionKey: "mysecurerandomencryptionkey12345!"