version: '3.9'

services:
  filebeat:
    image: filebeat:8.6.1
    container_name: filebeat
    build: .
    user: root
    command:
      - -e
      - --strict.perms=false
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro,Z
      - /var/log/:/var/log/
      - type: bind
        source: /var/lib/docker/containers
        target: /var/lib/docker/containers
        read_only: true
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
    environment:
      FILEBEAT_INTERNAL_PASSWORD: ${FILEBEAT_INTERNAL_PASSWORD:-}
      BEATS_SYSTEM_PASSWORD: ${BEATS_SYSTEM_PASSWORD:-}
    restart: unless-stopped
    networks:
      - elk

networks:
  elk:
    name: elk-net
    driver: bridge