{
 "title": "SNMP Exporter",
 "description": "Internal metrics of Prometheus' snmp_exporter",
 "tags": [
  "prometheus",
  "internal"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job_exporter",
    "label": "Exporter Job",
    "query": "query_result(snmp_exporter_build_info)"
   },
   {
    "name": "instance_exporter",
    "label": "Exporter Instance",
    "query": "query_result(snmp_exporter_build_info{job=~\"$job_exporter\"})"
   },
   {
    "name": "job_target",
    "label": "Target Job",
    "query": "query_result(snmp_scrape_pdus_returned)"
   },
   {
    "name": "instance_target",
    "label": "Target Instance",
    "query": "query_result(snmp_scrape_pdus_returned{job=~\"$job_target\"})"
   },
   {
    "name": "interval",
    "query": "5m,10m,15m,20m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"snmp\"}[$interval]) * 100",
     "legendFormat": "$interval rate"
    }
   ]
  },
  {
   "title": "Uptime [$interval]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance_exporter\",job=~\"$job_exporter\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"snmp\"}",
     "legendFormat": "RSS"
    }
   ]
  },
  {
   "title": "Request Errors",
   "type": "stat",
   "description": "Sum of errors in requests to the SNMP exporter during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum_over_time(snmp_request_errors_total{job=~\"$job_exporter\", instance=~\"$instance_exporter\"}[$interval]))"
    }
   ]
  },
  { "title": "resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"snmp\"}[$interval])",
     "legendFormat": "Irate"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"snmp\"}[$interval])",
     "legendFormat": "$interval rate"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"snmp\"}",
     "legendFormat": "RSS"
    },
    {
     "expr": "go_memstats_next_gc_bytes{job=\"snmp\"}",
     "legendFormat": "Next GC"
    },
    {
     "expr": "go_memstats_alloc_bytes{job=\"$job_exporter\", instance=\"$instance_exporter\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  { "title": "durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Collection Duration, $interval rate",
   "type": "timeseries",
   "description": "Duration of collections by the SNMP exporter by module.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(snmp_collection_duration_seconds_sum{job=~\"$job_exporter\", instance=~\"$instance_exporter\"}[$interval])",
     "legendFormat": "{{ module }}"
    }
   ]
  },
  {
   "title": "Unexpected PDUs, $interval rate",
   "type": "timeseries",
   "description": "Unexpected Go types in a PDU.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "snmp_unexpected_pdu_type_total", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "build info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Build info",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "snmp_exporter_build_info{job=~\"$job_exporter\"}"
    }
   ]
  }
 ]
}