{
 "title": "SNMP Network Monitoring",
 "description": "Network Details From Prometheus SNMP Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "source", "label": "Source", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(ifOperStatus, instance)"
    }
   },
   {
    "name": "ifName",
    "query": {
     "query": "query_result(ifOperStatus{instance=\"$instance\"})"
    }
   },
   {
    "name": "interval",
    "query": "5m,10m,15m, 20m, 30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "job_target",
    "label": "Target Job",
    "query": {
     "query": "query_result(snmp_scrape_pdus_returned)"
    }
   },
   {
    "name": "instance_target",
    "label": "Target Instance",
    "query": {
     "query": "query_result(snmp_scrape_pdus_returned{job=~\"$job_target\"})"
    }
   },
   {
    "name": "Device",
    "query": {
     "query": "query_result(sum by (instance)(ifInOctets{job=\"snmp\"}))"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(ifInOctets{job=\"snmp\",instance=\"$Device\"})"
    }
   },
   { "name": "Job", "query": { "query": "label_values(ifHClnOctets,job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Admin Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifAdminStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Oper Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifOperStatus{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Last Change",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{instance=\"$instance\"} - on(instance) ifLastChange{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifHighSpeed{instance=\"$instance\",ifName=\"$ifName\"}*1000000 or ifSpeed{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "MTU",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ifMtu{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Total PDUs returned",
   "type": "stat",
   "description": "Total PDUs returned across all selected target jobs and target instances. Averaged over the selected time period in Grafana.",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(snmp_scrape_pdus_returned{job=~\"$job_target\", instance=~\"$instance_target\"})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifType_info{instance=\"$instance\",ifName=\"$ifName\"}"
    }
   ]
  },
  {
   "title": "Total In",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCInOctets{job=\"snmp\"}[$__range]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Total Out",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(delta(ifHCOutOctets{job=\"snmp\"}[$__range]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Max In (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCInOctets{job=\"snmp\"}[5m]))",
     "legendFormat": "In"
    }
   ]
  },
  {
   "title": "Max Out (Current)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(irate(ifHCOutOctets{job=\"snmp\"}[5m]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "$Interface",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 6 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m])  or irate(ifInOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m]) ",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m])  or irate(ifOutOctets{job='snmp',instance='$Device',ifDescr=~'$Interface'}[5m]) ",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Walk Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "snmp_scrape_walk_duration_seconds{job=~\"$job_target\", instance=~\"$instance_target\"}",
     "legendFormat": "{{ instance }} [via {{ job }}]"
    }
   ]
  },
  {
   "title": "Scrape Duration by Instance",
   "type": "timeseries",
   "description": "Sum of scrape durations for a specific instance.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (instance) (snmp_scrape_duration_seconds)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "PDUs returned, $interval avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(snmp_scrape_pdus_returned{job=~\"$job_target\", instance=~\"$instance_target\"}[$interval])",
     "legendFormat": "{{instance}} [via {{job}}]"
    }
   ]
  },
  {
   "title": "Scrape Duration by Job",
   "type": "timeseries",
   "description": "Sum of scrape durations for a specific job.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (job) (snmp_scrape_duration_seconds)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "In (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"snmp\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out (Current)",
   "type": "bargauge",
   "description": "Max: 10MB  \nRed Status: 9MB",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"snmp\"}[5m])",
     "legendFormat": "{{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Out / In",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{job=\"snmp\"}[5m])",
     "legendFormat": "Out: {{ifName}} ({{ifAlias}})"
    },
    {
     "expr": "-irate(ifHCInOctets{job=\"snmp\"}[5m])",
     "legendFormat": "In: {{ifName}} ({{ifAlias}})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sysUpTime{job=\"snmp\"} * 10",
     "legendFormat": "In"
    }
   ]
  }
 ]
}