rules_folder: custom_rules
run_every:
  minutes: 1
buffer_time: 
  minutes: 15
es_host: 52.66.221.21
es_port: 9200
start_time: "now"
es_username: "elastic"
es_password: "elastic123"
use_ssl: False
writeback_index: elastalert_index
writeback_alias: elastalert_alias
alert_time_limit: 
 days: 2
smtp_host: smtp.gmail.com
smtp_port: 25
from_addr: shadikul.test@gmail.com
