version: '3.7'

services:
  elasticsearch:
    image: elasticsearch:${ELASTIC_VERSION}
    container_name: elasticsearch
    build:
      context: elasticsearch/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
      discovery.type: single-node
    networks:
      - elk
    restart: unless-stopped

  logstash:
    image: logstash:${ELASTIC_VERSION}
    container_name: logstash
    build:
      context: logstash/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - 5044:5044
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

  kibana:
    image: kibana:${ELASTIC_VERSION}
    container_name: kibana
    build:
      context: kibana/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - 5601:5601
    # environment:
    #   KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD:-}
    networks:
      - elk
    depends_on:
      - elasticsearch
    restart: unless-stopped

networks:
  elk:
    driver: bridge

volumes:
  setup:
  elasticsearch:

# sudo docker stop $(sudo docker ps -a -q); sudo docker rm $(sudo docker ps -a -q)
# vim extensions/filebeat/filebeat-compose.yml --> extensions--> filebeat --> filebeat-compose.yml --> volumes: /var/log/nginx/:/var/log/
# vim extensions/filebeat/config/filebeat.yml --> extensions--> filebeat --> config -->filebeat.yml --> filebeat.inputs: paths: /var/log/*.log
# docker-compose -f docker-compose.yml -f extensions/filebeat/filebeat-compose.yml up -d --build
# docker exec -it elasticsearch /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana
# vim kibana/config/kibana.yml --> Paste the password of kibana into kibana--> config--> kibana.yml--> elasticsearch.password: line
# docker-compose restart kibana
# Visit http://IP:5601 --> Username: elastic --> Password: elastic123
# Credentials have been declared in the .env folder and mounted from the docker-compose file Environment part
